openapi: 3.0.0
info:
  title: Test
  version: 1.0.0
paths:
  /test:
    post:
      requestBody:
        $ref: "./test_schemas.yaml#/components/schemas/Request"
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: "./test_schemas.yaml#/components/schemas/Response"
components:
  schemas:
    Request:
      $ref: "./test_schemas.yaml#/components/schemas/Request"
    Response:
      $ref: "./test_schemas.yaml#/components/schemas/Response"

